$ this tests that an error occurs when an attempt is made to access an out of bounds index (0) in the tuple
letting a be (2, true)
find b : int(1..2)
such that b = a[0]